import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { preview } from "../assets";
import { getRandomPrompt } from "../utils";
import { FormField, Loader } from "../components";

let CreatePost = () => {
  let navigate = useNavigate();
  let [form, setform] = useState({
    name: "",
    prompt: "",
    photo: "",
  });
  let [generatingImg, setgeneratingImg] = useState(true);
  let [loading, setloading] = useState(false);
  let generateImage = () => {};
  let handleSubmit = () => {};
  let handleChange = (e) => {
    setform({ ...form, [e.target.value]: e.target.value });
  };
  let handleSupriseMe = () => {
    const randomPrompt = getRandomPrompt(form.prompt);
    setform({ ...form, prompt: randomPrompt });
  };

  return (
    <section className="w-full  ">
      <div>
        <h1 className="font-bold text-[#222328] text-2xl">Create</h1>
        <p className="mt-2 text-[#666e75] text-sm max-w-full ">
          {" "}
          Create imaginative and visually stunning website generated by DALL-E
          AI and share them with the community
        </p>
      </div>
      <form className="mt-16" onSubmit={handleSubmit}>
        <div className="flex flex-col gap-5">
          <FormField
            LabelName="Your Name"
            type="text"
            name="name"
            placeholder="yaswanth"
            value={form.name}
            handleChange={handleChange}
          />
          <FormField
            LabelName="Prompt"
            type="text"
            name="Prompt"
            placeholder="a sea otter with a pearl earring"
            value={form.prompt}
            handleChange={handleChange}
            isSupriseMe
            handleSupriseMe={handleSupriseMe}
          />
          <div className="relative bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500  flex justify-center items-center ">
            {form.photo ? (
              <img
                src={form.photo}
                alt={form.prompt}
                className="w-full h-full object-contain"
              />
            ) : (
              <img
                src={preview}
                alt="preview"
                className="w-9/12 h-9/12 object-contain opacity-40"
              />
            )}
            {generatingImg && (
              <div className="absolute inset-0 z-0 flex justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-b-lg ">
                <Loader />
              </div>
            )}
          </div>
        </div>
        <div className="mt-5 flex gap-5">
          <button
            type="button"
            onClick={generateImage}
            className="text-white bg-green-700 font-medium rounded-md text-sm w-full sm:w-auto py-2.5 text-center "
          >
            {generatingImg ? "Generating..." : "Generate"}
          </button>
        </div>
        <div className="mt-10">
          <p className="mt-2 text-[#666e75] text-sm ">
            Once you have created the imgae you want, you can share with others
            in community
          </p>
          <button
            type="submit"
            className="mt-3 text-white bg-[#6469ff] font-medium rounded-md text-sm w-full sm:w-auto text-center "
          >
            {loading ? "sharing..." : "share with the community"}
          </button>
        </div>
      </form>
    </section>
  );
};

export default CreatePost;
